update workflows

diff --git a/.github/actions/4-identition/6-grammar/action.yml b/.github/actions/4-identition/6-grammar/action.yml
--- a/.github/actions/4-identition/6-grammar/action.yml
+++ b/.github/actions/4-identition/6-grammar/action.yml
@@ -92,13 +92,13 @@ runs:
       run: |
         if [[ '${{ inputs.failure_status }}' == 'true' ]]; then
       
-          git config --global user.name "$GITHUB_ACTOR"
-          git config --global --add safe.directory "$GITHUB_WORKSPACE"
-          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
-
-          REMOTE_REPO="https://$GITHUB_ACTOR:$GH_TOKEN@github.com/$GITHUB_REPOSITORY.git"
-          git clone --single-branch --branch gh-pages $REMOTE_REPO gh-pages && cd gh-pages
-          git add . && git commit --allow-empty -m "rerun due to job failure" && git push
+          curl -s -X POST \
+            -H "Authorization: token $GH_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" \
+            -d '{"event_type": "retry_workflow", "client_payload": {"original_run_id": "$GITHUB_RUN_ID"}}'
+            echo -e "Rerun workflow since there is failure happen on the previous jobs"
+          exit 1
   
         else
 
@@ -157,7 +157,7 @@ runs:
             git commit --allow-empty -m "Update GitHub workflows and configurations"
             git push origin v0
 
-            #Change the setting of default brance
+            #Change the setting of default branch
             curl -s -X PATCH \
               -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
@@ -166,48 +166,29 @@ runs:
             echo "Created v0 branch and set it as default"
           fi
 
-          AUTH="Authorization: Bearer $GH_TOKEN"
-          VERSION="X-GitHub-Api-Version: 2022-11-28"
-          ACCEPT="Accept: application/vnd.github+json"
-          RESPONSE=$(curl -s -L -H "$AUTH" -H "$VERSION" -H "$ACCEPT" "https://api.github.com/repos/$TARGET_REPOSITORY/actions/runners")
-          STATUS=$(echo "$RESPONSE" | jq -r --arg NAME "$RUNNER_TITLE" '.runners[] | select(.name == $NAME).status')
+          # Commit and push changes
+          git add . && git commit --allow-empty -m "$MESSAGE" && git push
 
-          if [[ "$STATUS" != "online" ]]; then
- 
+          if [[ "$TARGET_REPOSITORY" != *"eq19/"* ]]; then
+            # Unpublish existing GitHub Pages
+            curl -s -X DELETE \
+              -H "Authorization: token $GH_TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/$TARGET_REPOSITORY/pages > /dev/null
+  
+            # Disable GitHub Pages
+            curl -s -X PATCH \
+              -H "Authorization: token $GH_TOKEN" \
+              -H "Accept: application/vnd.github.v3+json" \
+              https://api.github.com/repos/$TARGET_REPOSITORY/pages \
+              -d '{"build_type":"legacy","source":null}' > /dev/null
+
+            # Trigger a dispaches action
             curl -s -X POST \
               -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
-              "https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches" \
-              -d '{"event_type": "retry_workflow", "client_payload": {"original_run_id": "$GITHUB_RUN_ID"}}'
-              echo -e "\nDispatched to https://github.com/${{ env.GITHUB_REPOSITORY }}/actions"
-            exit 1
- 
-          else
-   
-            # Commit and push changes
-            git add . && git commit --allow-empty -m "$MESSAGE" && git push
-
-            if [[ "$TARGET_REPOSITORY" != *"eq19/"* ]]; then
-              # Unpublish existing GitHub Pages
-              curl -s -X DELETE \
-                -H "Authorization: token $GH_TOKEN" \
-                -H "Accept: application/vnd.github.v3+json" \
-                https://api.github.com/repos/$TARGET_REPOSITORY/pages > /dev/null
-  
-              # Disable GitHub Pages
-              curl -s -X PATCH \
-                -H "Authorization: token $GH_TOKEN" \
-                -H "Accept: application/vnd.github.v3+json" \
-                https://api.github.com/repos/$TARGET_REPOSITORY/pages \
-                -d '{"build_type":"legacy","source":null}' > /dev/null
-
-              # Trigger a dispaches action
-              curl -s -X POST \
-                -H "Authorization: token $GH_TOKEN" \
-                -H "Accept: application/vnd.github.v3+json" \
-                "https://api.github.com/repos/$TARGET_REPOSITORY/dispatches" \
-                -d '{"event_type": "trigger_action", "client_payload": {"env": "prod", "version": "1.0"}}'
-              echo -e "\nDispatched to https://github.com/${{ env.TARGET_REPOSITORY }}/actions"
-            fi  
-          fi
+              "https://api.github.com/repos/$TARGET_REPOSITORY/dispatches" \
+              -d '{"event_type": "trigger_action", "client_payload": {"env": "prod", "version": "1.0"}}'
+            echo -e "\nDispatched to https://github.com/${{ env.TARGET_REPOSITORY }}/actions"
+          fi  
         fi
